---
- hosts: appserver
  become: yes
  tasks:
  - name: install git, wget and tree on nodes using loops
    apt:
     name: "{{ item }}"
     status: present
    with_items:
     - git
     - wget
     - tree